/* codes.h -- made by sstg_to_c 2.0 from sdcl.scn (by way of sdcl.table created by sstg 2.0) */

/* Character Classes */
#define LT_BACKSLASH (0)
#define LT_BANG (1)
#define LT_CBRACE (2)
#define LT_COLON (3)
#define LT_CPAREN (4)
#define LT_DIGIT (5)
#define LT_DOLLAR (6)
#define LT_EOF (7)
#define LT_EOL (8)
#define LT_EQUAL (9)
#define LT_LETTER (10)
#define LT_OBRACE (11)
#define LT_OPAREN (12)
#define LT_SLASH (13)
#define LT_POUND (14)
#define LT_DQUOTE (15)
#define LT_SEMI (16)
#define LT_SPACE (17)
#define LT_UNDER (18)
#define LT_UNDEFINED (19)

/* Action Codes */
#define AC_ADDGET (0)
#define AC_IGNGET (1)
#define AC_IGNNOP (2)
#define AC_IGNERR (3)
#define AC_IGNINL (4)
#define AC_BLKGET (5)
#define AC_KILGET (6)

/* Token Codes */
#define TC_ASSIGN (0)
#define TC_COLON (1)
#define TC_EOF (2)
#define TC_EOL (3)
#define TC_IDENT (4)
#define TC_INTEGER (5)
#define TC_LABEL (6)
#define TC_SINGLE (7)
#define TC_SPACE (8)
#define TC_STRING (9)
#define TC_CBRACE (10)
#define TC_CPAREN (11)
#define TC_DCLSTMT (12)
#define TC_OBRACE (13)
#define TC_OPAREN (14)
#define TC_OTHER (15)
#define TC_QUOTED (16)
#define TC_SEMI (17)
#define TC_BREAK (18)
#define TC_DO (19)
#define TC_ELSE (20)
#define TC_FOR (21)
#define TC_IF (22)
#define TC_NEXT (23)
#define TC_REPEAT (24)
#define TC_UNTIL (25)
#define TC_WHILE (26)
#define TC_UNKNOWN (27)

/* Start state */
#define ST_START (1)

/* Accept State */
#define ST_ACCEPT (0)

